name: snowflake_snapshot
description: ''
version: 0.0.1
author: null
language: sql
buildSystem: ''
buildSystemDetails: null
pipelines: {}
datasets: {}
templates: {}
jobs:
  jobs/orders_snapshot_job:
    name: orders_snapshot_job
    description: ''
    fabricUID: 10
    scheduler:
      Prophecy: {}
    cloudProvider: null
    jobSize: null
    scheduleCron: None
    timeout: null
    alerting:
      emails: ''
      onStart: false
      onSuccess: false
      onFailure: false
    pipelines: []
    jobClusterMode:
      clusterMode:
        Single: {}
      clusterId: null
    enabled: null
    createdAt: '2024-02-08 12:08:55'
    author: haresh@prophecy.io
gemContainer:
  languageVersion: ''
  gemLibsVersion: ''
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2024-02-08 06:04:43'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
  businessRules: {}
subgraphs: {}
sqlModels:
  .prophecy/metadata/sqlmodels/orders_model:
    name: orders_model
    schema:
      providerType: Snowflake
      fields:
      - name: ORDER_ID
        dataType:
          type: Number
      - name: ORDER_DATE
        dataType:
          type: Date
      - name: STATUS
        dataType:
          type: String
      - name: UPDATED_DATE
        dataType:
          type: Date
      - name: ACTIVE_FLAG
        dataType:
          type: String
    description: null
    author: haresh@prophecy.io
    files:
    - models/orders_model.sql
    - .prophecy/ide/models/orders_model.json
    sqlDependencies:
      models: []
      datasets: []
      seeds: []
      sources: []
      snapshots: []
    createdAt: '2024-02-08 06:15:16'
sqlSnapshots:
  .prophecy/metadata/sqlsnapshots/orders_snapshot:
    name: orders_snapshot
    schema:
      providerType: Snowflake
      fields:
      - name: ORDER_ID
        dataType:
          type: Number
      - name: ORDER_DATE
        dataType:
          type: Date
      - name: STATUS
        dataType:
          type: String
      - name: UPDATED_DATE
        dataType:
          type: Date
      - name: ACTIVE_FLAG
        dataType:
          type: String
    description: null
    author: nathan+blackrock@prophecy.io
    files:
    - snapshots/orders_snapshot.sql
    - .prophecy/ide/snapshots/orders_snapshot.json
    sqlDependencies:
      models: []
      datasets: []
      seeds: []
      sources: []
      snapshots: []
    createdAt: '2024-07-22 18:00:01'
sqlTests: {}
sqlMacros: {}
sqlSeeds:
  .prophecy/metadata/sqlseeds/orders_data:
    name: orders_data
    schema:
      providerType: Snowflake
      fields:
      - name: order_id
        dataType:
          type: Number
      - name: order_date
        dataType:
          type: Date
      - name: status
        dataType:
          type: String
      - name: updated_date
        dataType:
          type: Date
    description: null
    author: haresh@prophecy.io
    files:
    - seeds/orders_data.csv
    createdAt: '2024-02-08 06:05:19'
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline:
  name: sqlPipeline
  description: null
  author: haresh@prophecy.io
  createdAt: '2024-02-08 06:04:43'
dependencies: '[]'
projectDependencies: {}
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
